name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-webui-automation-test:
    # VM
    # if you have image in docker, can try another OS 
    runs-on: ubuntu-latest

    steps:
    # Download Repo
    - uses: actions/checkout@v3
    # Setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      # install Browser      
    - name: Setup Chrome
      # You may pin to the exact commit or the version.
      # uses: browser-actions/setup-chrome@c485fa3bab6be59dce18dbc18ef6ab7cbc8ff5f1
      uses: browser-actions/setup-chrome@v1.2.0
      
      # Setup Gradlew
    - name: Setup gradlew
      run: chmod +x gradlew
      
      # Execute gradlew command for running cucumber test
    - name: Execute Test
      run: ./gradlew cucumber
      
      #Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.2
      if: always()
      with:
        name: Cucumber Report
        path: reports
        
      # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: reports
      
    
        
